apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      imagePullSecrets:
        - name: younjei
      containers:
        - name: url-shortener
          image: younjei/url-shortener:1.2.5
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: geoip-volume
              mountPath: /geoip/
      volumes:
        - name: geoip-volume
          hostPath:
            path: /home/ec2-user/geoip/