spring:
  profiles:
    active: dev
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/url
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379

server:
  forward-headers-strategy: framework

keycloak:
  realm: project
  auth-server-url: http://localhost:55360/auth
  resource: url
  credentials:
    secret: PMO5hgl9Qz1lCYksJKYOWGYYwxKt90oY

geoip:
  db-path: "/Users/younjei/dev/GeoLite2-City.mmdb"